Repository etclabscore/ethereum-json-rpc-specification, pull requests merged in 2019-05, with the labels that each got.

#8 fix: spelling errors
  openrpc.json
Labels: bug, enhancement

#12 fix: add youtube video link for walkthrough
  README.md
Labels: enhancement

#15 fix: add client releases
  .circleci/config.yml
  .node-version
  .releaserc
  openrpc.json
  package-lock.json
  package.json
Labels: enhancement

#16 fix: remove release-web from circleci
  .circleci/config.yml
Labels: bug

#17 fix: revert to 1.0.4 of @open-rpc/typings
  package-lock.json
Labels: bug

#18 fix(circleci): add npm token usage for release
  .circleci/config.yml
Labels: bug

#19 fix(circleci): all caps on NPM_TOKEN
  .circleci/config.yml
Labels: bug

#22 Fix/cargo token
  package-lock.json
  package.json
Labels: bug

#25 fix: remove unused schema
  openrpc.json
Labels: bug
